// const mongoose = require('mongoose');

// // MongoDB Model
// const Students = mongoose.model('Students', new mongoose.Schema({
//     id: String,
//     roll_number: String,
//     admission_no:String,
//     student_name:String,
//     college:String,
//     branch:String,
//     passout_Year:String,
//     ssc_percent:String,
//     inter_percent:String,
//     diploma_percent:String,
//     btech_percent:String,
//     backlogs:String,
//     date_of_birth:String,
//     blood_group:String,
//     category:String,
//     nationality:String,
//     religion:String,
//     mother_tongue:String,
//     entrance_type:String,
//     rank:String,
//     joining_date:String,
//     seat_type:String,
//     admission_type:String,
//     mobile:String,
//     email:String,
//     official_mail:String,
//     scholarship:String,
//     phc:String,
//     father_name:String,
//     annual_income:String,
//     mother_name:String,
//     mother_mobile_no:String,
//     identification_marks:String,
//     corresponding_address:String,
//     permanent_address:String,
//     // Add more fields as needed
// }), 'Students');
// models/StudentData.js
const mongoose = require('mongoose');

const studentDataSchema = new mongoose.Schema({
    // id: String,
    roll_number: String,
    admission_no:String,
    student_name:String,
    college:String,
    branch:String,
    passout_Year:String,
    ssc_percent:String,
    inter_percent:String,
    diploma_percent:String,
    btech_percent:String,
    backlogs:String,
    date_of_birth:String,
    blood_group:String,
    category:String,
    nationality:String,
    religion:String,
    mother_tongue:String,
    entrance_type:String,
    rank:String,
    joining_date:String,
    seat_type:String,
    admission_type:String,
    mobile:String,
    email:String,
    official_mail:String,
    scholarship:String,
    phc:String,
    father_name:String,
    annual_income:String,
    mother_name:String,
    mother_mobile_no:String,
    identification_marks:String,
    corresponding_address:String,
    permanent_address:String,
  // Add other fields 
}, { collection: 'new students data' });

module.exports = mongoose.model('StudentData', studentDataSchema);
